package com.github.fish56.springdatajpa.entity;

import lombok.Data;

import javax.persistence.*;

@Data
@Entity
public class Wallet {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // 底层是通过id来关联的
    @OneToOne
    private Panda owner;

    private Integer money;
}
// create table wallet (id bigint generated by default as identity, money integer,
//    owner_id bigint, primary key (id))
