package com.github.fish56.springdatajpa.one2one;

import lombok.Data;
import lombok.experimental.Accessors;

import javax.persistence.*;

@Data
@Accessors(chain = true)
@Entity
public class Wallet {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * 底层是通过id来关联的
     */
    @OneToOne
    private Panda owner;

    /**
     * 钱包余额，单位： 分
     */
    private Integer money;
}
// create table wallet (id bigint generated by default as identity, money integer, owner_id bigint, primary key (id))
